[package]
name = "rust_aoc2023"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clio = "0.3.5"
enum-map = "2.7.3"
num = "0.4.3"
once_cell = "1.19.0"
regex = "1.10.3"
